# Generated by Django 6.0.4 on 2026-04-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('weight_kg', models.FloatField(default=1.0)),
                ('current_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shipments', to='api.branch')),
                ('origin_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipments', to='api.branch')),
            ],
            options={
                'db_table': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('status_description', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.shipment')),
            ],
            options={
                'db_table': 'TrackingHistory',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Musteri', 'Müşteri'), ('Kurye', 'Kurye'), ('Personel', 'Şube Çalışanı')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.branch')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Kurye'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_shipments', to='api.user'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'role': 'Musteri'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_shipments', to='api.user'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role': 'Musteri'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to='api.user'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity_kg', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('assigned_courier', models.OneToOneField(blank=True, limit_choices_to={'role': 'Kurye'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='api.user')),
            ],
            options={
                'db_table': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(max_length=50, unique=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_trips', to='api.branch')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_trips', to='api.branch')),
                ('shipments', models.ManyToManyField(related_name='trips', to='api.shipment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'db_table': 'Trips',
            },
        ),
    ]
