# Generated by Django 6.0.4 on 2026-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_options_task_is_active_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Yonetici', 'Yönetici'), ('Personel', 'Personel (Kurye)'), ('Kullanici', 'Kullanıcı (Müşteri)')], default='Kullanici', max_length=20),
        ),
    ]
