# Generated by Django 6.0.4 on 2026-05-11 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Onay_Bekliyor', 'Onay Bekliyor'), ('Yapilacak', 'Yapılacak'), ('Devam_Ediyor', 'Devam Ediyor'), ('Tamamlandi', 'Tamamlandı')], default='Onay_Bekliyor', max_length=20),
        ),
    ]
